### PR TITLE
OSX ARM64 build

### PR DESCRIPTION
**Pull request by wietsedv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR is based on #10

### CODE REVIEW

**Comment by tonigi** [comment]
Thanks, but apparently it doesn't build. It's all very cryptic IMHO. Perhaps it's just a matter of waiting for dependencies to become available.

**Comment by wietsedv** [comment]
I don't think it's a dependency problem. dtw-python does not have many dependencies and the ones it does have are already supported. It seems to be a solvable numpy cross-compilation specification problem, so I'll try to fix it later today. :)

**Comment by tonigi** [comment]
Perhaps the (implicit?) requirement of numpy 1.16? Is there a "better" baseline or best practice for it?

**Comment by wietsedv** [comment]
It seems to have something to do with that indeed. Conda automatically requires numpy 1.16, but this is not really a problem with other packages. In any case, numpy is at least an actual runtime requirement of dtw-python, but I'm not sure how/whether it is required at build time. Also, I'm not 100% clear on how cross-compilation, numpy and the build/host/run requirements are exactly linked together.

So unless someone sees at a glance what is going wrong, I'll just try some different things and see how that affects resuls. I cannot really test this locally, since it is a cross compilation issue that does not affect my local build.

**Comment by tonigi** [comment]
Still not building... This package is as basic as it gets, requiring only numpy (any version) and cython.   Is there any simple recipe from which one can take inspiration?  Thanks!

**Comment by tonigi** [comment]
@conda-forge-admin, please rerender

**Comment by tonigi** [comment]
After some wrangling, the bot's ARM migration worked. I suppose this PR is equivalent to that, so closing.

**Pull request closed without merging**
