### PR TITLE
bump to 1.4

### PR DESCRIPTION
**Pull request by bernt-matthias**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@conda-forge-admin, please rerender

**Comment by bernt-matthias** [comment]
@conda-forge-admin, please rerende

**Comment by tonigi** [comment]
What? 1.4.0 is not out

**Review by tonigi — COMMENTED** [review]
This can't be right. There is no 1.4 version!

**Comment by bernt-matthias** [comment]
Apparently I confused this with https://pypi.org/project/dtw/ .. can you explain the difference?

**Comment by tonigi** [comment]
They are independent implementations. I can only speak for mine. The objective is a feature-complete equivalent of the venerable R package [dtw](https://cran.r-project.org/package=dtw). I have a focus on flexibility, i.e. extensive support for all DTW-style algorithm variants, constraints, etc.  Homepage is https://dynamictimewarping.github.io .

**Comment by bernt-matthias** [comment]
Then sorry for the noise. And thanks a lot for the clarifciation.

**Pull request closed without merging**
